#!/bin/sh

logger "Starting H3 auto recovery script"
NO_POWER_OFF="/tmp/no_poweroff"

cmdline=`cat /proc/cmdline`
case "$cmdline" in
	*"root=/dev/"*)
	logger "Kernel started with root= command line parameter, exiting"
	exit 0
	;;
    *"emergency_type="*)
    EMC_TYPE=`echo $cmdline | awk -F'emergency_type=' '{print $2}' 2>/dev/null`
    ;;
esac
logger "BOOT as emergency mode: $EMC_TYPE"

if [ -e "/dev/mmcblk1" ]; then
	TARGET=/dev/mmcblk1
	TYPE="MMC 2 (eMMC)"
elif [ -e "/dev/mmcblk0" ]; then
	TARGET=/dev/mmcblk0
	TYPE="MMC 0 (SD)"
else
	logger "No SD/eMMC device found"
	exit 0
fi

leds_on()
{
    local prefix="/sys/class/leds/QPT_LED"

    for num in $@
    do
        echo heartbeat > "${prefix}${num}/trigger"
    done
}

leds_off()
{
    local prefix="/sys/class/leds/QPT_LED"

    for num in $@
    do
        echo none > "${prefix}${num}/trigger"
    done
}

export_mmc()
{
    logger "Exporting $TYPE ($TARGET)"

    echo "0" > /sys/bus/platform/devices/sunxi_usb_udc/otg_role

    modprobe -r g_mass_storage
    modprobe g_mass_storage file=$TARGET removable=0 ro=0 stall=0 iProduct="Allwinner device $TYPE"

    echo "2" > /sys/bus/platform/devices/sunxi_usb_udc/otg_role

    logger "Done"

    touch $NO_POWER_OFF
}

recovery_partX()
{
    local TARF=$1
    local PART=$2

    [ -f "$TARF" ] && {
        logger "recovery $PART from $TARF ..."

        echo `date` >> /mnt/recovery.log
        echo "$TARF -> $PART" >> /mnt/recovery.log

        zcat ${TARF} > ${PART}
    }
}

do_recovery()
{
    #part4 is backup storage
    mount ${TARGET}p4 /mnt || {
        logger "mount recovery data part failed"
        leds_off 2 3
        export_mmc
        exit 0
    }
    # part1 root-fs
    recovery_partX /mnt/rootfs.img.gz ${TARGET}p1 && leds_off 2
    # part2 opt: qpt-utils
    recovery_partX /mnt/opt.img.gz ${TARGET}p2 && leds_off 3
    # part3 vars
    recovery_partX /mnt/vars.img.gz ${TARGET}p3 && leds_off 4

    umount /mnt && leds_off 5

    logger "Shutting down recovery"

    [ ! -f "$NO_POWER_OFF" ] && poweroff
}


############################ main ###############################

leds_on 2 3 4 5

case "$EMC_TYPE" in
    1)
        logger "GPIO key reset pressed force recovery ..."
        do_recovery
    ;;
    2)
        # mmcblk0p3 var have the recovery flags
        mount ${TARGET}p3 /mnt || exit 0
        [ -f /mnt/.auto_recovery ] || {
            logger "Soft reset BUT no flag file found, Please do it manual ..."
            umount /mnt
            leds_off 2
            export_mmc
            exit 0
        }
        umount /mnt
        do_recovery
    ;;
    *)
        logger "unknow emergency mode ... exit~!"
    ;;
esac

leds_off 2 3 4

logger "finished recovery export fs to USB-HOST..."
export_mmc

# echo "0" > /sys/bus/platform/devices/sunxi_usb_udc/otg_role
# modprobe -r g_mass_storage
